### PR TITLE
Unsliced

### PR DESCRIPTION
**Pull request by treeowl**
Unsliced vectors. I basically applied or reproduced the effects of) most of the commits following the addition of slicing, but without slicing. I still need to do my type-splitting commit. While I was at it, I made some improvements for performance purposes.

### CODE REVIEW

**Comment by treeowl** [comment]
Some more low-hanging fruit: We should never do `Array.fromList n . reverse`. Rather, we should write a function that builds an array from a list *backwards* and use that. That way we won't have to allocate a reversed list we'll never need again.

**Done**

**Comment by travitch** [comment]
What happened to the history? Did you go back and replay the history somehow? I'll take a look at squashing this tomorrow

**Comment by treeowl** [comment]
Preserving the history while working seemed too hard, so I just based off an old commit. We can eventually squash all my stuff and rebase on master. Or whatever. I'm not so good with this git stuff.

**Comment by treeowl** [comment]
I'm working through rebasing this now. Bleh!

**Comment by treeowl** [comment]
Closing in favor of #17.

**Pull request closed without merging**
